site_name: Maude's Tech Notes
site_description: Technical notes on IoT protocols (Matter, WiFi 7) and CPE software architectures (prpl, RDK-B, OpenSync).
site_author: Maude
site_url: https://maudes.github.io/tech-notes

copyright: "&copy; 2026"

theme:
  name: material
  language: en 
  font:
    text: Muli
    code: Roboto Mono
  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs # 頂部選單欄
    - navigation.sections
    - navigation.top # 回到頂部按鈕
    - search.suggest
    - search.highlight
    - content.code.copy # 代碼複製按鈕

nav:
  - Home: index.md
  - English Blog: 
      - blog-en/index.md
  - 中文部落格: 
      - blog-zh/index.md
  - Others: 
      - others/index.md
  - My CV: https://maudes.github.io/cv

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/maudes
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/meng-hsueh-shen
    - icon: fontawesome/brands/medium
      link: https://medium.com/@maudeshen
  blog:
    authors:
      Maude:
        name: Maude
        avatar: https://github.com/maudes.png
        url: https://github.com/maudes

plugins:
  - search
  - blog:
      blog_dir: .           
      post_dir: .        
      authors: true
      pagination_per_page: 10
      post_readtime: true
      # date_format: "%B %d, %Y"
      archive: false      
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex: # 支援 LaTeX 公式
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - admonition

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
